version: '3.1'

services:

  wordpress:
    image: wordpress:5-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: laba
      WORDPRESS_DB_PASSWORD: h3ll0L4B4
      WORDPRESS_DB_NAME: laba
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laba
      MYSQL_USER: laba
      MYSQL_PASSWORD: h3ll0L4B4
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  - /mnt/assolaba-html:/var/www/html
  - /mnt/assolaba-db:/var/lib/mysql
